import Head from 'next/head'
import { AppData } from '../components/AppData';
import { Basket } from '../components/Basket';
import { Categories } from '../components/Categories'
import { Products } from '../components/Products'
import { wrapper } from '../store';
import { categoryApi, productApi } from '../store/features';
import styles from '../styles/Home.module.css'

export const getServerSideProps = wrapper.getServerSideProps((store) => async () => {

  store.dispatch(productApi.endpoints.getProducts.initiate());
  store.dispatch(categoryApi.endpoints.getCategories.initiate());


  await Promise.all([...store.dispatch(productApi.util.getRunningQueriesThunk()), ...store.dispatch(categoryApi.util.getRunningQueriesThunk())]);

  return {
    props: {}
  }
})

export default function Home() {
  console.log("rendered index");

  return (
    <div className={styles.container}>
      <Head>
        <title>Redux Toolkit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the next.js Redux Toolkit Test Page
        </h1>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(2, 1fr)", width: "100%", justifyContent: "center" }}>
          <Basket />
          <AppData />
        </div>
        <Categories />
        <Products />
      </main>
    </div>
  )
}
